# Importing Libraries

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


# Importing Dataset

In [14]:
dataset = pd.read_csv('./hiring.csv')
X = dataset.iloc[:, : -1].values
Y = dataset.iloc[:, 3].values


In [15]:
print(X)

[['North' 5 50000]
 ['South' 7 60000]
 ['East' 3 45000]
 ['West' 10 75000]
 ['North' 8 68000]
 ['South' 4 52000]
 ['East' 6 58000]
 ['West' 9 72000]
 ['North' 2 41000]
 ['South' 5 56000]
 ['East' 11 80000]
 ['West' 7 62000]
 ['North' 6 57000]
 ['South' 3 46000]
 ['East' 9 69000]
 ['West' 4 49000]
 ['North' 10 71000]
 ['South' 12 86000]
 ['East' 1 40000]
 ['West' 2 42000]
 ['North' 8 67000]
 ['South' 5 55000]
 ['East' 6 59000]
 ['West' 4 48000]
 ['North' 9 70000]
 ['South' 7 61000]
 ['East' 3 47000]
 ['West' 6 60000]
 ['North' 5 53000]
 ['South' 10 73000]
 ['East' 2 43000]
 ['West' 8 66000]
 ['North' 4 50000]
 ['South' 6 58000]
 ['East' 3 46000]
 ['West' 5 54000]
 ['North' 7 62000]
 ['South' 11 81000]
 ['East' 9 69000]
 ['West' 4 51000]
 ['North' 10 74000]
 ['South' 12 87000]
 ['East' 1 39000]
 ['West' 3 45000]
 ['North' 6 58000]
 ['South' 8 65000]
 ['East' 7 62000]
 ['West' 9 71000]
 ['North' 5 53000]
 [nan 2 40000]
 ['West' 11 89000]]


In [16]:
print(Y)

['Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes'
 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes']


# Handling Missing Values (NaN)

In [17]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [18]:
print(X)

[['North' 5.0 50000.0]
 ['South' 7.0 60000.0]
 ['East' 3.0 45000.0]
 ['West' 10.0 75000.0]
 ['North' 8.0 68000.0]
 ['South' 4.0 52000.0]
 ['East' 6.0 58000.0]
 ['West' 9.0 72000.0]
 ['North' 2.0 41000.0]
 ['South' 5.0 56000.0]
 ['East' 11.0 80000.0]
 ['West' 7.0 62000.0]
 ['North' 6.0 57000.0]
 ['South' 3.0 46000.0]
 ['East' 9.0 69000.0]
 ['West' 4.0 49000.0]
 ['North' 10.0 71000.0]
 ['South' 12.0 86000.0]
 ['East' 1.0 40000.0]
 ['West' 2.0 42000.0]
 ['North' 8.0 67000.0]
 ['South' 5.0 55000.0]
 ['East' 6.0 59000.0]
 ['West' 4.0 48000.0]
 ['North' 9.0 70000.0]
 ['South' 7.0 61000.0]
 ['East' 3.0 47000.0]
 ['West' 6.0 60000.0]
 ['North' 5.0 53000.0]
 ['South' 10.0 73000.0]
 ['East' 2.0 43000.0]
 ['West' 8.0 66000.0]
 ['North' 4.0 50000.0]
 ['South' 6.0 58000.0]
 ['East' 3.0 46000.0]
 ['West' 5.0 54000.0]
 ['North' 7.0 62000.0]
 ['South' 11.0 81000.0]
 ['East' 9.0 69000.0]
 ['West' 4.0 51000.0]
 ['North' 10.0 74000.0]
 ['South' 12.0 87000.0]
 ['East' 1.0 39000.0]
 ['West' 3.0 45000.0]
 [

# Encoding Categorical Data

## Encoding Independent Variable

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(), [0])
], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [20]:
print(X)

[[0.0 1.0 0.0 0.0 0.0 5.0 50000.0]
 [0.0 0.0 1.0 0.0 0.0 7.0 60000.0]
 [1.0 0.0 0.0 0.0 0.0 3.0 45000.0]
 [0.0 0.0 0.0 1.0 0.0 10.0 75000.0]
 [0.0 1.0 0.0 0.0 0.0 8.0 68000.0]
 [0.0 0.0 1.0 0.0 0.0 4.0 52000.0]
 [1.0 0.0 0.0 0.0 0.0 6.0 58000.0]
 [0.0 0.0 0.0 1.0 0.0 9.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 2.0 41000.0]
 [0.0 0.0 1.0 0.0 0.0 5.0 56000.0]
 [1.0 0.0 0.0 0.0 0.0 11.0 80000.0]
 [0.0 0.0 0.0 1.0 0.0 7.0 62000.0]
 [0.0 1.0 0.0 0.0 0.0 6.0 57000.0]
 [0.0 0.0 1.0 0.0 0.0 3.0 46000.0]
 [1.0 0.0 0.0 0.0 0.0 9.0 69000.0]
 [0.0 0.0 0.0 1.0 0.0 4.0 49000.0]
 [0.0 1.0 0.0 0.0 0.0 10.0 71000.0]
 [0.0 0.0 1.0 0.0 0.0 12.0 86000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 40000.0]
 [0.0 0.0 0.0 1.0 0.0 2.0 42000.0]
 [0.0 1.0 0.0 0.0 0.0 8.0 67000.0]
 [0.0 0.0 1.0 0.0 0.0 5.0 55000.0]
 [1.0 0.0 0.0 0.0 0.0 6.0 59000.0]
 [0.0 0.0 0.0 1.0 0.0 4.0 48000.0]
 [0.0 1.0 0.0 0.0 0.0 9.0 70000.0]
 [0.0 0.0 1.0 0.0 0.0 7.0 61000.0]
 [1.0 0.0 0.0 0.0 0.0 3.0 47000.0]
 [0.0 0.0 0.0 1.0 0.0 6.0 60000.0]
 [0.0 1.0 0.0 0.

## Encoding Dependent Variable

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [22]:
print(Y)

[1 0 0 1 1 1 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0
 1 0 0 0 1 1 1 1 1 1 1 0 0 1]


# Splitting the Dataset into Training Set and Testing Set

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [24]:
print(X_train)
print(X_test)

[[0.0 0.0 1.0 0.0 0.0 10.0 73000.0]
 [0.0 0.0 0.0 1.0 0.0 9.0 71000.0]
 [0.0 0.0 1.0 0.0 0.0 12.0 87000.0]
 [0.0 0.0 0.0 1.0 0.0 4.0 51000.0]
 [0.0 0.0 1.0 0.0 0.0 5.0 55000.0]
 [0.0 1.0 0.0 0.0 0.0 10.0 74000.0]
 [1.0 0.0 0.0 0.0 0.0 9.0 69000.0]
 [0.0 0.0 0.0 1.0 0.0 2.0 42000.0]
 [0.0 1.0 0.0 0.0 0.0 9.0 70000.0]
 [0.0 0.0 1.0 0.0 0.0 3.0 46000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 39000.0]
 [0.0 0.0 1.0 0.0 0.0 12.0 86000.0]
 [1.0 0.0 0.0 0.0 0.0 7.0 62000.0]
 [0.0 1.0 0.0 0.0 0.0 7.0 62000.0]
 [0.0 0.0 0.0 1.0 0.0 4.0 48000.0]
 [0.0 1.0 0.0 0.0 0.0 8.0 68000.0]
 [1.0 0.0 0.0 0.0 0.0 3.0 46000.0]
 [1.0 0.0 0.0 0.0 0.0 9.0 69000.0]
 [0.0 0.0 0.0 1.0 0.0 8.0 66000.0]
 [1.0 0.0 0.0 0.0 0.0 11.0 80000.0]
 [0.0 1.0 0.0 0.0 0.0 5.0 53000.0]
 [0.0 0.0 1.0 0.0 0.0 8.0 65000.0]
 [0.0 0.0 0.0 1.0 0.0 5.0 54000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 40000.0]
 [0.0 1.0 0.0 0.0 0.0 8.0 67000.0]
 [0.0 0.0 1.0 0.0 0.0 7.0 61000.0]
 [1.0 0.0 0.0 0.0 0.0 6.0 58000.0]
 [0.0 0.0 0.0 1.0 0.0 9.0 72000.0]
 [0.0 1.0 0.0 0

# Splitting the Dataset into Training Set and Testing Set

In [25]:
from sklearn.model_selection import train_test_split;
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1);

# Feature Scaling

In [26]:
print(X_train)

[[0.0 0.0 1.0 0.0 0.0 10.0 73000.0]
 [0.0 0.0 0.0 1.0 0.0 9.0 71000.0]
 [0.0 0.0 1.0 0.0 0.0 12.0 87000.0]
 [0.0 0.0 0.0 1.0 0.0 4.0 51000.0]
 [0.0 0.0 1.0 0.0 0.0 5.0 55000.0]
 [0.0 1.0 0.0 0.0 0.0 10.0 74000.0]
 [1.0 0.0 0.0 0.0 0.0 9.0 69000.0]
 [0.0 0.0 0.0 1.0 0.0 2.0 42000.0]
 [0.0 1.0 0.0 0.0 0.0 9.0 70000.0]
 [0.0 0.0 1.0 0.0 0.0 3.0 46000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 39000.0]
 [0.0 0.0 1.0 0.0 0.0 12.0 86000.0]
 [1.0 0.0 0.0 0.0 0.0 7.0 62000.0]
 [0.0 1.0 0.0 0.0 0.0 7.0 62000.0]
 [0.0 0.0 0.0 1.0 0.0 4.0 48000.0]
 [0.0 1.0 0.0 0.0 0.0 8.0 68000.0]
 [1.0 0.0 0.0 0.0 0.0 3.0 46000.0]
 [1.0 0.0 0.0 0.0 0.0 9.0 69000.0]
 [0.0 0.0 0.0 1.0 0.0 8.0 66000.0]
 [1.0 0.0 0.0 0.0 0.0 11.0 80000.0]
 [0.0 1.0 0.0 0.0 0.0 5.0 53000.0]
 [0.0 0.0 1.0 0.0 0.0 8.0 65000.0]
 [0.0 0.0 0.0 1.0 0.0 5.0 54000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 40000.0]
 [0.0 1.0 0.0 0.0 0.0 8.0 67000.0]
 [0.0 0.0 1.0 0.0 0.0 7.0 61000.0]
 [1.0 0.0 0.0 0.0 0.0 6.0 58000.0]
 [0.0 0.0 0.0 1.0 0.0 9.0 72000.0]
 [0.0 1.0 0.0 0

In [27]:
from sklearn.preprocessing import StandardScaler;
sc = StandardScaler();
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:]);
X_test[:, 3:] = sc.transform(X_test[:, 3:]);

# Final Processed Data

In [28]:
print('Processed X_train:');
print(X_train);
print('Processed Y_train:');
print(Y_train);

Processed X_train:
[[0.0 0.0 1.0 -0.5773502691896258 0.0 1.164863548305887
  1.0152443058892369]
 [0.0 0.0 0.0 1.7320508075688774 0.0 0.8296510164193007 0.855677420877176]
 [0.0 0.0 1.0 -0.5773502691896258 0.0 1.8352886120790592
  2.1322125009736626]
 [0.0 0.0 0.0 1.7320508075688774 0.0 -0.8464116430136303
  -0.739991429243432]
 [0.0 0.0 1.0 -0.5773502691896258 0.0 -0.5111991111270441
  -0.42085765921931034]
 [0.0 1.0 0.0 -0.5773502691896258 0.0 1.164863548305887
  1.0950277483952673]
 [1.0 0.0 0.0 -0.5773502691896258 0.0 0.8296510164193007
  0.6961105358651152]
 [0.0 0.0 0.0 1.7320508075688774 0.0 -1.5168367067868027
  -1.4580424117977056]
 [0.0 1.0 0.0 -0.5773502691896258 0.0 0.8296510164193007
  0.7758939783711456]
 [0.0 0.0 1.0 -0.5773502691896258 0.0 -1.1816241749002165
  -1.1389086417735839]
 [1.0 0.0 0.0 -0.5773502691896258 0.0 -1.8520492386733889
  -1.6973927393157966]
 [0.0 0.0 1.0 -0.5773502691896258 0.0 1.8352886120790592
  2.052429058467632]
 [1.0 0.0 0.0 -0.577350269189625